### GET request for a card
GET http://localhost:5000/api/cards/615c8ea9a51d9bfd67175935 HTTP/1.1


### Create a card
POST http://localhost:5000/api/cards/ HTTP/1.1
content-type: application/json

{
  "listId": "6166fcd91dbdc694fc7ea8b1",
  "card": {
    "title": "card 11:38"
  }
}