### Create a new list
POST http://localhost:5000/api/lists/ HTTP/1.1
content-type: application/json

{
  "boardId": "615b2c8b16da3c988bc0ab1f",
  "list": {
    "title": "My list 10"
  }
}

### Updates a list
PUT http://localhost:5000/api/lists/61608bdd1e6882b0bb9ed70a HTTP/1.1
content-type: application/json

{ 
  "title": "its friday 1:19",
  "position": 4
}

