### Create a new list
POST http://localhost:5000/api/lists/ HTTP/1.1
content-type: application/json

{
  "boardId": "615b2c8b16da3c988bc0ab1a",
  "list": {
    "title": "My list 2"
  }
}

### Updates a list
PUT http://localhost:5000/api/lists/1 HTTP/1.1
content-type: application/json

{
  "title": "Updated title",
  "position": 137882
}

